### ISSUE TITLE
Gringotts causing Issues with DynmapTowny (hope someone here can help me since on Dynmap or the Towny support they can't)

### ISSUE THREAD

**Issue by moabist** [nikosgram13/Gringotts#100]
**Describe the bug**
--> Screenshot

**To Reproduce**
Can't tell tbh 
but appeared after 2-3 Days of normal usage and since then spams the consol after starting the Server

**Expected behavior**
Nothing - No Error 

**Screenshots**
![i need help](https://user-images.githubusercontent.com/105125842/177363860-54e03e36-e0b1-4cfc-b6c1-946e1ee42891.PNG)

**Desktop (please complete the following information):**
 - Server Type: Spigot
 - Server Version: 1.18.2
 - Gringotts Version: 2.12.2

**Additional context**

**Comment by nikosgram** [comment]
Looking into it :)

**Comment by moabist** [comment]
What did you find out so far? :)

**Comment by nikosgram** [comment]
The issue caused by a false null check statement of Gringotts of the Towny's nation entity. Gringotts-Towny should have that problem fixed :)

https://github.com/nikosgram/gringotts-towny/blob/main/src/main/java/com/oglofus/gringotts/towny/nation/NationHolderProvider.java#L82
