### ISSUE TITLE
Ebean Unhappy - DOA issues

### ISSUE THREAD

**Issue by nikosgram** [nikosgram13/Gringotts#104]
**Describe the bug**
NewUpdated to 2.12.3, getting error on startup, plugin does not enable. Error log: https://paste.md-5.net/zuloduxeni.cs
Using latest Paper 1.19.2.

**Desktop (please complete the following information):**
 - Server Type: PaperMC/Spigot/Purpur
 - Server Version: 1.19.2
 - Gringotts Version: 2.12.3

**Comment by nikosgram** [comment]
Looks like the issue had to do with the compiler target been on 17. ebean was really unhappy with that. Even though papermc recommending using it.

https://papermc.io/using-the-api

![image](https://user-images.githubusercontent.com/3318873/189056436-653d8ffb-243a-4497-9dcd-9cb42c59c9c2.png)

Rolling back to compiler target 8 fixes the issue... WHAT A DAY!!!!

**Comment by edelmxnn** [comment]
How do i fix it if i use a Spigot Server?

Server: 1.19.2
Spigot: 1.19.2
---
Edit:
I tried to fix it but i am not smart enough to do so.
Ok i dont get any of this. So here is my question: will you update Towny-Gringotts as well, so i dont have to destroy my brain trying to do so?

**Comment by nikosgram** [comment]
I wasn't aware that Gringotts-Towny had the same issue. It shouldn't as it's independent of Gringotts. I gonna have a look on it today :)

**Comment by nikosgram** [comment]
Hi @edelmxnn , The latest version of Gringotts-Towny should have the loading issue fixed :) 

https://github.com/nikosgram/gringotts-towny/releases/tag/2.12.4-SNAPSHOT
