### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [nikosgram13/Gringotts#105]
**Describe the bug**
Plugin does not load at all

**To Reproduce**
1. Add the plugin
2. Start server
3. Error logs at the very top on console

**Expected behavior**
The plugin to work

**Error Logs**
https://hastebin.com/nocazanobe.properties

**Desktop (please complete the following information):**
 - Server Type: PaperMC
 - Server Version: git-Paper-137 (MC: 1.19.2)
 - Gringotts Version: 2.12.3

**Additional context**
none

**Comment by nikosgram** [comment]
Hello,

There is already a issue reported yesterday describing the same issue. 

https://github.com/nikosgram/gringotts/issues/104
