### ISSUE TITLE
Non secured command (java exception)

### ISSUE THREAD

**Issue by Serafinowy** [nikosgram13/Gringotts#113]
**Describe the bug**
When you want to type "/money deposit" ArrayIndexOutOfBoundsException throws in the console. Error occurs at "MoneyExecutor.java:66".

**To Reproduce**
1. Type '/money deposit' in game

**Expected behavior**
It should display for ex. "Correct usage: /money deposit <amount>".

**Screenshots**
![Bez tytułu222](https://user-images.githubusercontent.com/54081699/193468652-a6a14897-4435-459f-8ccd-035ad819262e.png)

**Desktop (please complete the following information):**
 - Server Type: [e.g. PaperMC, Spigot]
 - Server Version: [e.g. 1.17.1-386]
 - Gringotts Version: [e.g. 2.12.2]

**Comment by nikosgram** [comment]
Hello @Serafinowy. That is really interesting :) 

Do you have Vault as part of the plugins?

**Comment by Serafinowy** [comment]
Yes, I have all required plugins and the error only occures when you type '/money withdraw/deposit' without any other arguments.
