### ISSUE TITLE
Withdrawing/depositing

### ISSUE THREAD

**Issue by BannedAdress** [nikosgram13/Gringotts#116]
**Describe the bug**
When trying to use the commands:

/money withdraw [amount]
/money deposit [ amount ] 
Returns: 
usage: /money [pay/give/take/set] [playerName/all/alloffline] [amount][%rand/1-1000%][1%[min-max]][playername]] (-s)

![image](https://user-images.githubusercontent.com/113264987/194407572-6431ea35-895a-4ed5-bf31-6f6fd5db851f.png)

![image](https://user-images.githubusercontent.com/113264987/194407636-301a2820-4b0a-43e1-976c-99c506e04844.png)

**Expected behavior**
it should just deposit/withdraw money. 

**Desktop (please complete the following information):**
 - Server Type PaperMC
 - Server Version: paper-1.19.2-141
 - Gringotts Version: [Gringotts v2.12.4-SNAPSHOT]

**Comment by nikosgram** [comment]
That is a weird behavior. I'll have a look :)

**Comment by OskarZyg** [comment]
+1, same issue here. takes the money but doesn't put it in the vault, then towny returns "you don't have that much"

**Comment by GroobleDierne** [comment]
Seems to be fixed
