### ISSUE TITLE
lag with gringotts

### ISSUE THREAD

**Issue by frogglen** [nikosgram13/Gringotts#117]
**Describe the bug**
im using gringotts its my production server with about 20 users and it seems to be causing some lag on my server

**Screenshots**
![gringotts](https://user-images.githubusercontent.com/6269642/195218920-1b7369fe-471d-4d17-9f36-a5db66276c78.png)

 - Server Type: purpur
 - Server Version: git-Purpur-1819 (MC: 1.19.2)*
 - Gringotts Version: gringotts-2.12.4-SNAPSHOT

**Comment by nikosgram** [comment]
I gonna have a look :)
