### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by 22Conner** [nikosgram13/Gringotts#119]
1.19.2 Spigot, I can't get it to work. It may or may not be a bug, but I believe I got uploaded it to the server correctly due to the gringotts towny working.
![Screen Shot 2022-10-14 at 4 05 37 PM](https://user-images.githubusercontent.com/108838947/195950855-7ca1813c-f203-4180-95e5-bc1a87f842ed.png)
![Screen Shot 2022-10-14 at 4 02 12 PM](https://user-images.githubusercontent.com/108838947/195950857-2355c863-2a47-4b91-ba43-4f797ed91ebd.png)

**Comment by nikosgram** [comment]
You'll need to include Vault :)

**Comment by 22Conner** [comment]
> You'll need to include Vault :)

ty

**Comment by 22Conner** [comment]
@nikosgram  I'm running into an issue where when I deposit money with towny it takes my gold but doesnt go through

https://user-images.githubusercontent.com/108838947/196091330-365c7161-4a68-4d69-b08e-bc4bba75e303.mp4
