### ISSUE TITLE
Quickshop isn't recognising offline players enderchest/inventory.

### ISSUE THREAD

**Issue by brandcrystal** [nikosgram13/Gringotts#136]
If the shop owner is offline it throws an internal error for quickshop with this following error from gringotts inside the console.

EconomyTransaction Failed, last error:Failed to deposit 1.0 to player 711321ac-6865-411d-a9be-0ad9cbf6b176 account. LastError: Gringotts: FAILURE - Insufficient space.

This happens even when the user has sufficient space.

(IF THE OWNER OF A SHOP SETS UP A VAULT, IT WORKS GREAT.) But i would really appreciate enderchest/inventory support for offline users as it doesn't seem to pick it up.

Latest version of Gringotts, minecraft 1.16.5 arclight/forge.

**Comment by brandcrystal** [comment]
Would love some help with this, thanks.

**Comment by Haui1112** [comment]
hi there! Same problem here with advanced region market (arm) on 1.19. Was using 2.12.4 SNAPSHOT

**Comment by nikosgram** [comment]
Hello :) Is it possible to reproduce the issue with Gringotts 2.12.5-SNAPSHOT? 

https://github.com/nikosgram/gringotts/releases/tag/2.12.5-SNAPSHOT
