### ISSUE TITLE
Gringotts Breaking Compatibility with Other Plugins on 2.12.5

### ISSUE THREAD

**Issue by Relaxing9** [nikosgram13/Gringotts#154]
**Describe the bug**
Gringotts is creating an NPE 

**To Reproduce**
1. Download Autorank & Gringotts (also have a Permissions Provider)
2. See example configuration below (additional context) for further information on how configured
3. Try to check if you completed an Autorank path and if Gringotts money reward is in the middle of the reward list it breaks the rest of the reward types.

**Expected behavior**
No errors to occur & you are able to receive all items without hassle. Due to this error I had to edit my Autorank configuration file to list Gringotts rewards as the last item on the list or else it breaks Autorank in handing out other rewards. I am guessing it has something to do with the new Shulker Box features. 

Issue is not present in 2.12.4-SNAPSHOT

**Desktop (please complete the following information):**
 - Server Type: PaperMC
 - Server Version: 1.19.4-550
 - Gringotts Version: 2.12.5

**Additional context**
[Example Autorank Configuration](https://paste.gg/p/anonymous/e2d5e9257b3a4d0999e37e8831567915)
[Error Generated for Gringotts when Integrated with Autorank](https://paste.gg/p/anonymous/f016eadad5394a3eb151ccfc1be8f22d)

Also breaks UltimateRewards when setting money as a reward, only downgrading to 2.12.4-SNAPSHOT resolves it.

**Comment by nikosgram** [comment]
Is it possible to share the Gringotts config? There is a possibility that the denomination type is empty or incorrect.

**Comment by nikosgram** [comment]
I made a few changes regards this issue. Can the problem be reproduced with Gringotts version 2.12.6-SNAPSHOT and send the log in this thread? 

You can find the Gringotts snapshot on the link below:

https://github.com/nikosgram/gringotts/releases/download/2.12.6-SNAPSHOT/gringotts-2.12.6-SNAPSHOT.jar

**Comment by Relaxing9** [comment]
> Is it possible to share the Gringotts config? There is a possibility that the denomination type is empty or incorrect.

Here is the config:
[Link](https://paste.gg/p/anonymous/73b22acd56284285a69daceba43ada47)
Will need to test your Snapshot that you provided though.

**Comment by Relaxing9** [comment]
It not longer errors with UltimateRewards as for Autorank will need to manually configure that, but if it is already not showing it on UltimateRewards, it shouldn't be able to reproduce it on Autorank either.

Will attempt to set that up though to verify.

**Comment by Relaxing9** [comment]
No longer able to replicate this error on Autorank either no logs generated. Thanks for solving the issue.

I'll leave it for you to lock.
