### ISSUE TITLE
Any 1.16.5 version ?

### ISSUE THREAD

**Issue by JLSkyzer** [nikosgram13/Gringotts#156]
Hello, i search a version for 1.16.5 please

**Comment by nikosgram** [comment]
Gringotts 2.11.2 should be what you are looking for. Please keep in mind that this is an old version, and we are not planning on supporting version 1.16.5 on the latest version, so I'll not be able to help with any issues you might have with an old version like this.

https://github.com/nikosgram/gringotts/releases/download/2.11.2-SNAPSHOT-rf77e523/Gringotts-2.11.2-SNAPSHOT-rf77e523.jar
