### ISSUE TITLE
Vaults Cannot Be Created Due To Error

### ISSUE THREAD

**Issue by Ethansito** [nikosgram13/Gringotts#77]
Howdy!

I am running a 1.12.2 Spigot server with Gringotts. Whenever I try to create a vault, nothing happens in the game, and I get this error in the console:

`28.11 10:13:05 [Server] ERROR Could not pass event SignChangeEvent to Gringotts v2.12.1`

I also have this issue using v2.12.2. I tried using earlier versions of Gringotts, but the jars would not make the config files when I restarted the server. Could I have some help, please?

**Comment by nikosgram** [comment]
Hello @Ethansito .

Can you try this version:

https://github.com/nikosgram/gringotts/releases/download/2.11.2-SNAPSHOT-rf77e523/Gringotts-2.11.2-SNAPSHOT-rf77e523.jar

2.11.2 💯
