### ISSUE TITLE
1.18 Support?

### ISSUE THREAD

**Issue by OmegaShaman** [nikosgram13/Gringotts#80]
Well, it's pretty self explanatory ofc.

**Comment by nikosgram** [comment]
Isn't already working properly on 1.18? :O

**Comment by MuniuDev** [comment]
![image](https://user-images.githubusercontent.com/8275106/144488038-8c3b49f7-5af3-45f3-a837-195d4d176e39.png)
I belive there is a shutdown issue, at least for me. Not sure if it affects anything. Tested on newest release of paper.

**Comment by nikosgram** [comment]
I'm aware of this error, is not causing any issues though. :)

**Comment by nikosgram** [comment]
If you find a functionallity issue on 1.18, please feel free to reopen the ticket.
