### ISSUE TITLE
Vault creation error

### ISSUE THREAD

**Issue by Kv0th** [nikosgram13/Gringotts#81]
Always when one player of my server try to create his vault it work, but when he trys to use it the sign dissapers 

It might be a permission error, but i alredy gave them all the none op permissions in LP.

Sorry for any english error

**Comment by nikosgram** [comment]
Hello @Kv0th 

What is your current Gringotts version? 

Thanks :)

**Comment by Kv0th** [comment]
Looks like I solved the problem thanks anyway for the amazing plugin...
