### ISSUE TITLE
Towny - "You don't have that much" when /t deposit 1

### ISSUE THREAD

**Issue by AbsDataStruct** [nikosgram13/Gringotts#85]
**Describe the bug**
Using Gringotts-2.12.2 along with Towny-0.97.5.6 I could not succeed to make deposit on the town bank account :
I have emerald items in my inventory, they are actually removed from my inventory but I've finally got the message "You don't have that much" and no money are deposited.

**To Reproduce**
1. Create a new town 
2. Get 64 emerald items
3. make a deposit on the town account of 10 emeralds with /t deposit 10
4. There is 54 emeralds left in my inventory
5. see "You don't have that much" message
6. No money are deposited
7. the gringotts:balance displays :
Your current balance: 54 Emeralds
Vault balance: 0 Emeralds
Invenroty balance: 54 Emeralds
See Screenshot

**Expected behavior**
Since the Emeralds are taken successfully from the inventory, other plugin should be able to receive the money using Vault

**Screenshots
![emerald](https://user-images.githubusercontent.com/78984720/147730912-9305fa17-1be8-47a4-b50f-cf9ce443916a.png)
**

**Desktop (please complete the following information):**
 - Server Type: paper
 - Server Version: 1.18.1-105
 - Gringotts Version: 2.12.2

**Additional context**
I thought first it was a problem with Towny, but they told me that they are using the vault virtual money manager to process the payment, so they suggest that Gringotts could not implement correctly vault virtualization of money ...

If I did something wrong, I don't understand what. It looks like Towny and Gringotts can work together.
I really need help to understand the problem ... Thanks for any comment or suggestion in order to solve and improve this wonderful plugin.

**Comment by kurkii** [comment]
I have this same issue, paper 1.18.1, towny 0.97.5.11, gringotts 2.12.2

**Comment by MetalPinguinInc** [comment]
I also ran into this issue, in my case I did not have a Town Vault for the town I just made. You can make a Town Vault by placing a chest, putting a sign over it and typing [Town vault] on the sign (Including the [] brackets!) 

The real issue seems to be that Gringotts does not send a proper error message and just takes the funds.

**Comment by Frithy0** [comment]
Same for me with Towny 0.98.2.6

**Comment by nikosgram** [comment]
Hello, 

That is an interesting issue. Looking into it. :)

**Comment by AbsDataStruct** [comment]
hey thanks !!!! ^_^
I still cannot make that server without it  😉

________________________________

**Comment by OskarZyg** [comment]
+1
