### ISSUE TITLE
Worldguard vault type not working

### ISSUE THREAD

**Issue by dfeneck** [nikosgram13/Gringotts#89]
**Describe the bug**
Vault's for worldguards regions aren't registering.

**Desktop (please complete the following information):**
 - Server Type: Spigot
 - Server Version: 1.18.1
 - Gringotts Version: 2.12.2

**Comment by nikosgram** [comment]
Hello @dfeneck ,

I'm afraid is not a bug but on purpose as I dropped support of WorldGuard a while ago.

If lot of users request it back, I'll investigate into a better implementation of it :)

**Comment by dfeneck** [comment]
Okay well could you please update your spigot page and remove reference for that feature?

Any chance you could add custom vaults? I'm trying to setup a system where spent diamonds go to a "server bank"

**Comment by nikosgram** [comment]
Hmm, it's not in the current plans but you can always use a user that is operator as the "server bank" account.
