### ISSUE TITLE
vault_pattern configuration for towny vaults

### ISSUE THREAD

**Issue by TheUndermon** [nikosgram13/Gringotts#91]
**Is your feature request related to a problem? Please describe.**
The problem is localization. When on a non-english server it creates confusion when most of the plugin is translated, except the sign text    used to create vaults for Towny towns and nations.

**Describe the solution you'd like**
Create vault_pattern configuration option for Towny town and nation vaults.

**Comment by nikosgram** [comment]
Looking into it :)

**Comment by nikosgram** [comment]
Implementation committed 29be62d3c6cf049a920f80f06378ba7de8786749
