### ISSUE TITLE
Gringotts Worldguard

### ISSUE THREAD

**Issue by mardigiorgio** [nikosgram13/Gringotts#95]
It there a more in depth documentation about how gringotts hooks into world guard?

**Comment by spikehidden** [comment]
> It there a more in depth documentation about how gringotts hooks into world guard?

It doesn't anymore as far as I know.
The documentation seems to be out of date about worldguard support.

**Comment by nikosgram** [comment]
There is no worldguard support anymore I'm afraid. Mostly because of complications with the plugin.
