### ISSUE TITLE
New Config Options

### ISSUE THREAD

**Issue by Relaxing9** [nikosgram13/Gringotts#99]
**Is your feature request related to a problem? Please describe.**
My feature request is related to a server warning I receive on server startup
![image](https://user-images.githubusercontent.com/41935047/173861912-5f3f1511-2ae5-416d-b7cd-d210c82496d8.png)

**Describe the solution you'd like**
If possible, I would like config.yml options to disable plugin integration for the warned plugins (such as for Towny & Reserve, since I don't use them)

**Describe alternatives you've considered**
Haven't thought of any alternatives.

**Additional context**
None.

**Comment by nikosgram** [comment]
Looking into it :)
